export const IpcChannels = {
  dbPing: 'db:ping',
  projectCreate: 'project:create',
  projectList: 'project:list',
  projectOpen: 'project:open',
  projectDelete: 'project:delete',
  videoSelectFile: 'video:selectFile',
  imageSelectFile: 'image:selectFile',
  playerCreate: 'player:create',
  playerDelete: 'player:delete',
  eventCreate: 'event:create',
  eventDelete: 'event:delete',
  eventUpdateClip: 'event:updateClip',
  exportClip: 'export:clip',
  shotCreate: 'shot:create',
  systemCreate: 'system:create',
  systemDelete: 'system:delete',
  eventTypeCreate: 'eventType:create',
  seasonStats: 'season:stats',
  drawingCreate: 'drawing:create',
  playlistCreate: 'playlist:create',
  playlistDelete: 'playlist:delete',
  playlistAddItem: 'playlist:addItem',
  playlistRemoveItem: 'playlist:removeItem',
  playlistExport: 'playlist:export',
  statsExport: 'stats:export'
} as const
